//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKOMEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int idArticulo { get; set; }
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
        public string Descripcion_corta { get; set; }
        public string Descripcion_larga { get; set; }
        public string IMG { get; set; }
        public string Precio { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public int Cantidad { get; internal set; }
        public double SubTotal { get; internal set; }
    }
}
