//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKOMEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int idMensaje { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public int Estado { get; set; }
        public System.DateTime Created_at { get; set; }
        public int idPersona { get; set; }
    }
}
