//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKOMEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int idVenta { get; set; }
        public int idUsuario { get; set; }
        public string Detalles { get; set; }
        public string Importe { get; set; }
        public string SubTotal { get; set; }
        public string IVA { get; set; }
        public string Total { get; set; }
        public System.TimeSpan Fecha { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
    }
}
